[[VALIDATORS]]
public_key = "nHBA1Lk3rwhjHAa4LpzmWbTHJ7UXsw7eitdbwYd1ZNQxg47JoGbc"
attestation = "4618135620B3ACC797CA8AF6AB415EE2B4FE16847CEC444E0F2E9D2595121CEA67170BB5B4E87D32B474FBC9754D0A97571FEA1D4A6827DC98A7EBE5C303BA02"
network = "main"
owner_country = "us"
server_country = "us"
unl = "https://vl.ripple.com"


[[ACCOUNTS]]
# address = "r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV"
# desc = "Ripple-owned address from old ripple.txt file"
# Note: This doesn't prove ownership of an account unless the
#   "Domain" field of the account in the XRP Ledger matches the
#   domain this file was served from.

[[SERVERS]]
json_rpc = "https://s1.ripple.com:51234/"
ws = "wss://s1.ripple.com/"
peer = "https://s1.ripple.com:51235/"
desc = "General purpose server cluster"

[[SERVERS]]
json_rpc = "https://s2.ripple.com:51234/"
ws = "wss://s2.ripple.com/"
peer = "https://s2.ripple.com:51235/"
desc = "Full-history server cluster"

[[SERVERS]]
json_rpc = "https://s.testnet.rippletest.net:51234/"
ws = "wss://s.testnet.rippletest.net:51233/"
peer = "https://s.testnet.rippletest.net:51235/"
network = "testnet"
desc = "Test Net public server cluster"

[[PRINCIPALS]]
name = "Brett Salyer" # Primary spec author
email = "brettsalyer@gmail.com" # Not my real email address

# End of file